runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: backend.app
  login: required

- url: /(\d+)
  script: backend.app
  login: required

- url: /comment
  script: backend.app
  login: required

- url: /remove
  script: backend.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest